---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if (.Values.dnsEntry) }} 
    # From https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "{{ .Values.loadBalancerInternal | default true }}"
#    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsEntry }}
    # From https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsEntry }}
    {{- end }}    
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  ports:  
  - name: services
    port: {{ add 0 .Values.basePort }}
    protocol: TCP
    targetPort: {{ add 0 (.Values.basePortInsidePod | default .Values.basePort) }}
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 0 .Values.basePort }} {{ end }}
  {{- if (.Values.wildflyAdminUser) }} 
  - name: admin
    port: {{ add 1 .Values.basePort }}
    protocol: TCP
    targetPort: 9993
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 1 .Values.basePort }} {{ end }}
  {{- end }}
  {{- if (.Values.wildflyEnableDebug) and (eq .Values.wildflyEnableDebug "Yes") }} 
  - name: debug
    port: {{ add 2 .Values.basePort }}
    protocol: TCP
    targetPort: 8787
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 2 .Values.basePort }} {{ end }}
  {{- end }} 
  - name: edge-receive-0
    port: {{ add 0 .Values.edgeReceiverBasePort }}
    protocol: TCP
    targetPort: {{ add 0 (.Values.edgeReceiverBasePortInsidePod | default .Values.edgeReceiverBasePort) }}
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 0 .Values.edgeReceiverBasePort }} {{ end }}
  - name: petasos-0
    port: {{ add 0 .Values.petasosBasePort }}
    protocol: TCP
    targetPort: {{ add 0 (.Values.petasosBasePortInsidePod | default .Values.petasosBasePort) }}
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 0 .Values.petasosBasePort }} {{ end }}
  - name: petasos-1
    port: {{ add 1 .Values.petasosBasePort }}
    protocol: TCP
    targetPort: {{ add 1 (.Values.petasosBasePortInsidePod | default .Values.petasosBasePort) }}
    nodePort: {{ if (.Values.serviceType) and (eq .Values.serviceType "NodePort")}} {{ add 1 .Values.petasosBasePort }} {{ end }}
  selector:
    app: {{ .Values.serviceName }}
  type: {{ .Values.serviceType | default "LoadBalancer" }}
  {{- if (.Values.loadBalancerIP) }} 
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
